spring.application.name=Boot31_MVC_BankManagementSystem_Mini_Project

#view resolver configuration
spring.mvc.view.prefix=/WEB-INF/pages/
spring.mvc.view.suffix=.jsp

#Database connection
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/myeclipsedb
spring.datasource.username=root
spring.datasource.password=chiku

#Embedded server port number
#server.port=4041

#Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true

#Context path
#server.servlet.context-path=/BMS-CRUDOperation