spring.application.name=Boot22_UniversityCourseManagementSystem_UsingOneToMany


spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/myeclipsedb
spring.datasource.username=root
spring.datasource.password=chiku

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect